import = [
  # "~/.config/alacritty/tokyonight.toml"
  "~/.config/alacritty/tokyonight-storm.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/monokai_pro.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding = { x = 4, y = 0 }
startup_mode = "Maximized"
option_as_alt = "OnlyLeft"

[font]
normal = { family = "JetbrainsMono Nerd Font", style = "Regular" }
size = 16.0
offset = { x = 0, y = 2 }

