#!/usr/bin/env bash

pushd . >/dev/null

if [[ ! -L "$HOME/dotfiles" ]] && [[ ! -d "$HOME/dotfiles" ]]; then
    ln -s "$(pwd)" $HOME/dotfiles
fi

cd ~/dotfiles
mkdir -p ~/.config

for d in `find * -maxdepth 1 -type d -not -path ./.git`; do
    if [[ -f $d/link ]]; then
        cd $d
        echo "linking: $d"
        bash link
        cd ..
    fi
done

popd >/dev/null
