#!/usr/bin/env bash

CWD="$(pwd)"

[[ -L "$HOME/dotfiles" ]] || ln -s "$(pwd)" $HOME/dotfiles
cd ~/dotfiles

for d in `find . -type d -maxdepth 1 -not -path ./.git`; do
    if [[ -f $d/link ]]; then
        echo "running $d/link"
        cd $d
        bash link
        cd ..
    fi
done

cd $CWD
