---
- name: configure lua-language-server
  hosts: localhost
  gather_facts: no

  vars:
    lua_repo_dir: '{{ ansible_env.HOME }}/repos/lua-language-server'
    lua_build_dir: '{{ lua_repo_dir }}/3rd/luamake'

  tasks:

  - name: clone lua-language-server
    ansible.builtin.git:
      repo: https://github.com/sumneko/lua-language-server
      dest: '{{ lua_repo_dir }}'
      clone: true
      update: true

  - name: init submodules
    ansible.builtin.command:
      cmd: 'git submodule update --init --recursive'
      chdir: '{{ lua_repo_dir }}'
      creates: '{{ lua_build_dir }}'

  - name: compile lua-language-server
    ansible.builtin.command:
      cmd: './compile/install.sh'
      chdir: '{{ lua_build_dir }}'
      creates: '{{ lua_build_dir }}/build'

  - name: rebuild lua-language-server
    ansible.builtin.command:
      cmd: './3rd/luamake/luamake rebuild'
      chdir: '{{ lua_repo_dir }}'
      creates: '{{ lua_repo_dir }}/bin/*/lua-language-server'
