---
- name: markdown
  hosts: localhost
  gather_facts: false

  tasks:

  - name: macOS => install markdownlint-cli
    when: ansible_distribution == 'MacOSX'
    community.general.homebrew:
      name: 'markdownlint-cli'
      state: present
