---
- name: typescript language server
  hosts: localhost
  gather_facts: no

  tasks:

  - name: typescript-language-server
    community.general.npm:
      name: typescript-language-server
      global: yes
