---
- name: vim language server
  hosts: localhost
  gather_facts: no

  tasks:

  - name: vim-language-server
    community.general.npm:
      state: latest
      name: vim-language-server
      global: yes
