---
- name: configure base
  hosts: localhost
  gather_facts: no

  tasks:

  - name: ensure base directories
    ansible.builtin.file:
      path: "{{item}}"
      state: directory
    loop:
    - '{{ ansible_env.HOME }}/repos'
    - '{{ ansible_env.HOME }}/.config'


  - name: macOS => install base packages
    when: ansible_distribution == 'MacOSX'
    community.general.homebrew:
      name:
      - go
      - geckodriver
      - gsed
      - kubernetes
      - minikube
      - docker

  - name: Ubuntu => install base packages
    when: ansible_distribution == 'Ubuntu'
    apt:
      update_cache: yes
      name:
      - go
      - geckodriver
      - kubernetes

  - name: macOS => install homebrew casks
    when: ansible_distribution == 'MacOSX'
    community.general.homebrew_cask:
      name:
      - rectangle
