---
- name: configure nodejs
  hosts: localhost
  gather_facts: no

  tasks:

  - name: Ubuntu => add node repo
    when: ansible_distribution == 'Ubuntu'
    ansible.builtin.shell: 'curl -fsSL https://deb.nodesource.com/setup_17.x | sudo -E bash -'
    args:
      warn: false
      creates: '/etc/apt/sources.list.d/nodesource.list'

  - name: RedHat => add node module
    when: ansible_distribution == 'RedHat'
    become: true
    dnf:
      name: "@nodejs:16"
      state: present

  - name: Ubuntu => install nodejs
    when: ansible_distribution == 'Ubuntu'
    become: true
    ansible.builtin.apt:
      pkg: ["nodejs"]
      state: latest

  - name: RedHat => install nodejs
    when: ansible_distribution == 'RedHat'
    become: true
    package:
      name: nodejs
      state: latest

  - name: link .npmrc
    ansible.builtin.file:
      src: '{{ ansible_env.PWD }}/../../npm/npmrc'
      dest: '{{ ansible_env.HOME }}/.npmrc'
      state: link
