---
- name: preflight
  hosts: localhost

  tasks:

    - name: macOS => homebrew upgrade all
      when: ansible_distribution == 'MacOSX'
      community.general.homebrew:
        update_homebrew: yes
        upgrade_all: yes

