---
- name: configure ssh
  hosts: localhost

  tasks:

  - name: link .ssh/config
    ansible.builtin.file:
      src: "{{ lookup('env', 'GDRIVEDIR') }}/config/ssh/config"
      dest: '{{ ansible_env.HOME }}/.ssh/config'
      state: link

  - name: link .ssh/config.d/
    ansible.builtin.file:
      src: "{{ lookup('env', 'GDRIVEDIR') }}/config/ssh/config.d"
      dest: '{{ ansible_env.HOME }}/.ssh/config.d'
      state: link

  - name: ensure ssh keys
    ansible.builtin.shell:
      executable: zsh
      cmd: 'source ~/.zshenv && ensure_ssh_keys'
      creates: '{{ ansible_env.HOME }}/.ssh/keys'

