---
- name: configure tmux
  hosts: localhost
  gather_facts: false

  vars:
    tmux_plugin_dir: '{{ ansible_env.HOME }}/.config/tmux'

  tasks:

    - name: link .tmux.conf
      ansible.builtin.file:
        src: '{{ ansible_env.PWD }}/../../tmux/tmux.conf'
        dest: '{{ ansible_env.HOME }}/.tmux.conf'
        state: link
      register: new_tmux

    - name: tmux plugin manager
      ansible.builtin.git:
        repo: https://github.com/tmux-plugins/tpm
        dest: ~/.config/tmux/plugins/tpm

    - name: install tmux plugins
      command: "{{ansible_env.HOME}}/.config/tmux/plugins/tpm/bin/install_plugins"

    - name: update terminal descriptions
      when: new_tmux.changed
      block:
      - name: create temp build dir
        tempfile:
          state: directory
          suffix: terminfo
        register: tmp

      - name: download terminfo
        get_url:
          url: https://invisible-island.net/datafiles/current/terminfo.src.gz
          dest: "{{tmp.path}}/terminfo.src.gz"

      - name: unzip terminfo
        command: gunzip terminfo.src.gz
        args:
          chdir: "{{tmp.path}}"

      - name: load tmux definition
        command: "/usr/bin/env tic -xe tmux-256color {{tmp.path}}/terminfo.src"
