require('lcrown.packer')
require('lcrown.mason')
require('lcrown.sets')
require('lcrown.nvim-tree')
require('lcrown.formatting')
require('lcrown.devicons')
require('lcrown.treesitter')
require('lcrown.lsp')
require('lcrown.theme')
require('lcrown.telescope')
require('lcrown.nvim-comment')
require('lcrown.keymaps')
require('lcrown.terminal')
require('lcrown.misc')

-- require('lcrown.debugging')
-- require('lcrown.playground')
