#!/usr/bin/env bash

mkdir -p ~/.config/nvim

rm -f ~/.vimrc
rm -rf ~/.config/nvim/init.vim
rm -rf ~/.config/nvim/lua

ln -s ~/dotfiles/nvim/init.vim ~/.config/nvim/init.vim
ln -s ~/dotfiles/nvim/lua ~/.config/nvim/lua
