#!/usr/bin/env bash
mkdir -p ~/.config/nvim/plugin
mkdir -p ~/.config/nvim/after/plugin
mkdir -p ~/.config/nvim/lua/lcrown


which rg > /dev/null 2>&1 || brew install rg

for f in `find -E . -regex ".*\.vim$|.*\.lua$"`; do
    rm -rf ~/.config/nvim/$f
    ln -s ~/GoogleDrive/config/dotfiles/nvim/$f ~/.config/nvim/$f
done
