require'nvim-treesitter.configs'.setup {
  ensure_installed = {
    "python",
    "ruby",
    "go",
    "bash",
    "rust",
    "c",
    "c_sharp",
    "clojure",
    "comment",
    "cpp",
    "dockerfile",
    "elixir",
    "erlang",
    "fennel",
    "fish",
    "gomod",
    "graphql",
    "hcl",
    "hocon",
    "html",
    "http",
    "java",
    "javascript",
    "json",
    "json5",
    "kotlin",
    "latex",
    "julia",
    "lua",
    "make",
    "nix",
    "perl",
    "php",
    "r",
    "regex",
    "scss",
    "svelte",
    "toml",
    "tsx",
    "typescript",
    "vim",
    "vue",
    "yaml",
    "zig",
  },
  highlight = { enable = true },
  incremental_selection = { enable = true },
  textobjects = { enable = true },
  indent = {
    enable = true,
    disable = {
      "yaml",
      "python",
    },
  },
    -- playground = {
        -- enable = true,
        -- disable = {},
        -- updatetime = 25, -- Debounced time for highlighting nodes in the playground from source code
        -- persist_queries = false, -- Whether the query persists across vim sessions
        -- keybindings = {
            -- toggle_query_editor = 'o',
            -- toggle_hl_groups = 'i',
            -- toggle_injected_languages = 't',
            -- toggle_anonymous_nodes = 'a',
            -- toggle_language_display = 'I',
            -- focus_language = 'f',
            -- unfocus_language = 'F',
            -- update = 'R',
            -- goto_node = '<cr>',
            -- show_help = '?',
        -- },
    -- },
}
