return {
  {
    "nvim-treesitter/nvim-treesitter",
    event = "BufEnter",
    build = ":TSUpdate",
    config = function()
      require("nvim-treesitter.configs").setup({
        ensure_installed = {
          "bash",
          "c",
          "cmake",
          "comment",
          "cpp",
          "css",
          "diff",
          "dockerfile",
          "git_rebase",
          "gitattributes",
          "gitcommit",
          "gitignore",
          "go",
          "gomod",
          "graphql",
          "vimdoc",
          "html",
          "http",
          "javascript",
          "jq",
          "jsdoc",
          "json",
          "json5",
          "jsonc",
          "lua",
          "make",
          "markdown",
          "markdown_inline",
          "perl",
          "python",
          "regex",
          "ruby",
          "rust",
          "scss",
          "sql",
          "svelte",
          "terraform",
          "toml",
          "tsx",
          "typescript",
          "vim",
          "vue",
          "yaml",
        },
        highlight = { enable = true },
        indent = { enable = false, disable = { "html", "yaml", "python", "sh", "go" } },
      })
    end,
  }
}
