---
- import_playbook: include/preflight.yml
  tags: [always]

- import_playbook: include/base.yml
  tags: [base]

- import_playbook: include/tmux.yml
  tags: [tmux]

- import_playbook: include/ansible.yml
  tags: [ansible]

- import_playbook: include/irb.yml
  tags: [irb]

- import_playbook: include/zsh.yml
  tags: [zsh]

- import_playbook: include/pyenv.yml
  tags: [pyenv]

- import_playbook: include/nvim.yml
  tags: [nvim]

- import_playbook: include/mac.yml
  when: ansible_distribution == 'MacOSX'
  tags: [mac]

- import_playbook: include/keepassxc.yml
  when: ansible_distribution == 'MacOSX'
  tags: [keepassxc]

- import_playbook: include/openconnect.yml
  when: ansible_distribution == 'MacOSX'
  tags: [openfortivpn]

- import_playbook: include/ssh.yml
  when: ansible_distribution == 'MacOSX'
  tags: [ssh]
