---
- import_playbook: include/preflight.yml
  tags: [always]

- import_playbook: include/base.yml
  tags: [base]

- import_playbook: include/nodejs.yml
  tags: [nodejs]

- import_playbook: include/tmux.yml
  tags: [tmux]

- import_playbook: include/ansible.yml
  tags: [ansible]

- import_playbook: include/irb.yml
  tags: [irb]

- import_playbook: include/zsh.yml
  tags: [zsh]

- import_playbook: include/pyenv.yml
  tags: [pyenv]

- import_playbook: include/nvim.yml
  tags: [nvim]

- import_playbook: include/language-servers/efm.yml
  tags: [nvim, efm]

- import_playbook: include/language-servers/lua.yml
  tags: [nvim, lua]

- import_playbook: include/language-servers/rust.yml
  tags: [nvim, rust]

- import_playbook: include/language-servers/python.yml
  tags: [nvim, python]

- import_playbook: include/language-servers/bash.yml
  tags: [nvim, bash]

- import_playbook: include/language-servers/bash.yml
  tags: [nvim, bash]

- import_playbook: include/language-servers/vim.yml
  tags: [nvim, vim]

- import_playbook: include/language-servers/ansible.yml
  tags: [nvim, ansible]

- import_playbook: include/keepassxc.yml
  when: ansible_distribution == 'MacOSX'
  tags: [keepassxc]

- import_playbook: include/openfortivpn.yml
  when: ansible_distribution == 'MacOSX'
  tags: [openfortivpn]

- import_playbook: include/ssh.yml
  when: ansible_distribution == 'MacOSX'
  tags: [ssh]

