#!/usr/bin/env bash

rm -f ~/.zshrc
rm -f ~/.zshenv
rm -rf ~/.config/zsh

ln -s ~/dotfiles/zsh/zshrc ~/.zshrc
ln -s ~/dotfiles/zsh/zshenv ~/.zshenv
ln -s ~/dotfiles/zsh/zsh ~/.config/zsh

uname -a | grep Darwin >/dev/null && \
	ln -s ~/dotfiles/zsh/iterm2_shell_integration.zsh ~/.iterm2_shell_integration.zsh >/dev/null 2>&1

test -d ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting || git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
test -d ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions || git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
