# This file is sourced from ~/.zshrc and loads the rest of the zsh configs
#
# this file is the entrypoint when non-interactive shells open a zsh process

setopt aliases

export ZSH_CONF_DIR="$HOME/.config/zsh"

insert_path() { [ $SHLVL -eq 1 ] && export PATH="$1:$PATH" }
append_path() { [ $SHLVL -eq 1 ] && export PATH="$PATH:$1" }

case "$(uname -a)" in
    Darwin*)
        export OS="mac"
        ;;
    *WSL*)
        export OS="wsl"
        ;;
    *)
        export OS="linux"
        ;;
esac

if [ "$OS" = "mac" ]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
fi

# Source all my configs from the conf dir
for f in $ZSH_CONF_DIR/*.sh; do
    source $f
done

. "$HOME/.cargo/env"

export EDITOR="nvim"
export VISUAL="nvim"
