# uncomment this line to measure performance
# zmodload zsh/zprof

export ZSH=$HOME/.oh-my-zsh
ZSH_THEME="robbyrussell"
export TERM=xterm-256color

ulimit -n 1024

plugins=(
	git
	zsh-syntax-highlighting
	zsh-autosuggestions
	docker
)

source $ZSH/oh-my-zsh.sh
unsetopt AUTO_CD

export ZSH_CONF_DIR="$HOME/.config/zsh"

# Source all my configs from the conf dir
for f in $ZSH_CONF_DIR/*.sh; do
    source $f
done

# uncomment this line to display measured performance
# zprof

#
# If there's anything below this comment,
# it probably needs to be sorted into a file or somehow organized.
#
