# if [ "$TERM_PROGRAM" = "vscode" ]; then
#     tmux new-session -A -s vscode
# fi

# performance testing
# PS4='%D{%s.%9.}+%N:%i> '
# set -x

# auto attach to tmux on kitty and wsl
if [ -z $TMUX ]; then
    # attach to main if terminal is kitty
    if [[ "$TERM" = "xterm-kitty" ]] || [[ "$DOT_OS" = "wsl" ]]; then
        tmux new-session -A -s main
    fi
fi

export ZSH=$HOME/.oh-my-zsh
ZSH_THEME="robbyrussell"

ulimit -n 1024

plugins=(
    git
    zsh-autosuggestions
    docker
    zsh-syntax-highlighting
)

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=8'
ZSH_AUTOSUGGEST_MANUAL_REBIND=true

source $ZSH/oh-my-zsh.sh
unsetopt AUTO_CD

if [[ -d $HOME/.pyenv ]]; then
    export PYENV_ROOT="$HOME/.pyenv"
    export PATH="$PYENV_ROOT/bin:$PATH"
    eval "$(pyenv init - --no-rehash zsh)"
fi

compdef __start_kubectl k
source <(kubectl completion zsh)

setopt prompt_subst

bindkey -v
