# if [ "$TERM_PROGRAM" = "vscode" ]; then
#     tmux new-session -A -s vscode
# fi

# performance testing
# PS4=$'\\\011%D{%s%6.}\011%x\011%I\011%N\011%e\011'
# exec 3>&2 2>/tmp/zshstart.$$.log
# setopt xtrace prompt_subst
# zmodload zsh/zprof

if [ -z $TMUX ]; then
    if [[ "$TERM" = "xterm-kitty" ]]; then # attach to main if terminal is kitty
        tmux new-session -A -s main
    elif [[ "$TERM_PROGRAM" = "iTerm.app" ]]; then
        :
    elif [[ "$TERM_PROGRAM" = "vscode" ]]; then
        :
    elif [[ "$TERM_PROGRAM" = "WezTerm" ]]; then
        :
    elif [[ "$TERM_PROGRAM" = "ghostty" ]]; then
        # tmux new-session -A -s main
        :
    elif [[ "$TERM" = "xterm-256color" ]]; then # attach to main if terminal is alacritty/wezterm (this conflicts with vs code)
        tmux new-session -A -s main
    elif  [[ "$DOT_OS" = "wsl" ]]; then
        tmux new-session -A -s main
    fi
fi

export ZSH=$HOME/.oh-my-zsh
ZSH_THEME="robbyrussell"

ulimit -n 4096

plugins=(
    git
    zsh-autosuggestions
    docker
    zsh-syntax-highlighting
)

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=8'
ZSH_AUTOSUGGEST_MANUAL_REBIND=true

source $ZSH/oh-my-zsh.sh
unsetopt AUTO_CD

if [[ -d $HOME/.pyenv ]]; then
    export PYENV_ROOT="$HOME/.pyenv"
    export PATH="$PYENV_ROOT/bin:$PATH"
    eval "$(pyenv init - --no-rehash zsh)"
	eval "$(pyenv virtualenv-init -)"
fi

export PATH="$PATH:$HOME/.local/bin"

# use CTRL-Z to toggle between suspend and fg
fancy-ctrl-z () {
  if [[ $#BUFFER -eq 0 ]]; then
    BUFFER="fg"
    zle accept-line -w
  else
    zle push-input -w
    zle clear-screen -w
  fi
}
zle -N fancy-ctrl-z
bindkey '^Z' fancy-ctrl-z

setopt prompt_subst

# end performance testing
# unsetopt xtrace
# exec 2>&3 3>&-
# zprof
