---
- name: go
  hosts: localhost
  gather_facts: no

  tasks:

  - name: Linux => check if go version is downloaded
    when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'RedHat'
    stat:
      path: "{{ansible_env.HOME}}/src/go1.19.linux-amd64.tar.gz"
    register: go_archive_check

  - name: Linux => download go
    when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'RedHat'
    get_url:
      url: https://go.dev/dl/go1.19.linux-amd64.tar.gz
      dest: "{{ansible_env.HOME}}/src/go1.19.linux-amd64.tar.gz"
      mode: "0644"
    when: not go_archive_check.stat.exists

  - name: Linux => unarchive go
    when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'RedHat'
    unarchive:
      src: "{{ansible_env.HOME}}/src/go1.19.linux-amd64.tar.gz"
      dest: "{{ansible_env.HOME}}/src/"
      remote_src: true
    when: not go_archive_check.stat.exists
