---
- name: configure lua-language-server
  hosts: localhost
  gather_facts: false

  vars:
    lua_repo_dir: '{{ ansible_env.HOME }}/repos/lua-language-server'
    lua_build_dir: '{{ lua_repo_dir }}/3rd/luamake'

  tasks:

    - name: macOS => clone lua-language-server
      when: ansible_distribution == "MacOSX"
      ansible.builtin.git:
        repo: https://github.com/sumneko/lua-language-server
        dest: '{{ lua_repo_dir }}'
        version: HEAD
        clone: true
        update: true

    - name: macOS => init submodules
      when: ansible_distribution == "MacOSX"
      ansible.builtin.command:
        cmd: 'git submodule update --init --recursive'
        chdir: '{{ lua_repo_dir }}'
        creates: '{{ lua_build_dir }}'

    - name: macOS => compile lua-language-server
      when: ansible_distribution == "MacOSX"
      ansible.builtin.command:
        cmd: './compile/install.sh'
        chdir: '{{ lua_build_dir }}'
        creates: '{{ lua_build_dir }}/build'

    - name: macOS => rebuild lua-language-server
      when: ansible_distribution == "MacOSX"
      ansible.builtin.command:
        cmd: './3rd/luamake/luamake rebuild'
        chdir: '{{ lua_repo_dir }}'
        creates: '{{ lua_repo_dir }}/bin/*/lua-language-server'

    - name: install stylua
      community.general.cargo:
        name: stylua
