---
- name: rust
  hosts: localhost
  gather_facts: no

  tasks:

  - name: install rust
    shell:
      cmd: 'curl https://sh.rustup.rs -sSf | sh -s -- -y'
      creates: '{{ ansible_env.HOME }}/.cargo/env'

  - name: clone rust-analyzer
    git:
      repo: https://github.com/rust-lang/rust-analyzer.git
      dest: "{{ansible_env.HOME}}/repos/rust-analyzer"

  - name: install rust-analyzer
    command:
      cmd: cargo xtask install --server
      chdir: "{{ansible_env.HOME}}/repos/rust-analyzer"
      creates: "{{ansible_env.HOME}}/.cargo/bin/rust-analyzer"

  - name: install rustfmt
    command:
      cmd: rustup component add rustfmt
      creates: "{{ansible_env.HOME}}/.cargo/bin/rustfmt"

  - name: install clippy
    command:
      cmd: rustup component add clippy
      creates: "{{ansible_env.HOME}}/.cargo/bin/cargo-clippy"
